# -*- coding: utf-8 -*-
"""pyspark_note.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Fp0K5dZq9hqE3sKv2T0cKI20B2BN5RW

# Pyspark in colab
Reference: [使用 Google Colaboratory 跑 PySpark](https://medium.com/@chiayinchen/使用-google-colaboratory-跑-pyspark-625a07c75000)

### Install Java and Spark
"""

!apt-get -y install openjdk-8-jre-headless
!pip install pyspark

"""測試 Spark 是否成功安裝"""

from pyspark.sql import SparkSession
from pyspark import SparkContext

spark = SparkSession.builder.master("local").getOrCreate()
sc = SparkContext.getOrCreate()
rdd = sc.parallelize(["Hello Spark"])
counts = rdd.flatMap(lambda line: line.split(" ")) \
    .map(lambda word: (word, 1)) \
    .reduceByKey(lambda a, b: a + b) \
    .collect()
print(counts)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# from pyspark.sql import SparkSession
# from pyspark import SparkContext
# from pyspark.sql import SQLContext
# spark = SparkSession.builder.master("local").getOrCreate()
# sc = SparkContext.getOrCreate()
# sqlContext = SQLContext(sc)
# sdf = sqlContext.read.format('com.databricks.spark.csv') \
#     .options(header='true', inferschema='true') \
#     .load('./sample_data/california_housing_train.csv')
# 
# sdf.show()

"""Build datafram by Pandas"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# from pyspark import SparkContext
# from pyspark.sql import SQLContext
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# %matplotlib inline
# 
# sc = SparkContext.getOrCreate()
# sqlc = SQLContext(sc)
# df = pd.read_csv('./sample_data/california_housing_train.csv')
# sdf = sqlc.createDataFrame(df)

sdf.show()

sdf.filter(sdf['latitude'] >= 33).show(20)

# Find specific value by collect()[row][columns]
sdf.filter(sdf['latitude'] >= 33).collect()[0][1]

sdf.select('housing_median_age').distinct().show()

tmp = sdf.groupBy('housing_median_age').count().orderBy('count').toPandas()

plt.plot(tmp)
plt.show()

